### ISSUE TITLE
Error following the README orders.

### ISSUE THREAD

**Issue by YuliTshuva** [nmdp-bioinformatics/py-graph-imputation#32]
**Describe the bug**
After I clone the git repo, when I follow the README.md orders step by step, I get stuck in the part of ```from grim.grim import graph_freqs```. It seems to happen to a colleague of mine as well.

A solution that works for sure on **Linux OS** is:
```
git clone https://github.com/nmdp-bioinformatics/py-graph-imputation
cd py-graph-imputation/
make venv
source venv/bin/activate
make install
pip install -e .
```

Then, you can run it in the virtual environment like in the orders.

I would like to thank Pradeep for that thoughtful solution.

**Comment by pbashyal-nmdp** [comment]
You can get `py-graph-imputation` with `pip install py-graph-imputation`. See updated README
